[package]
name = "systemd-fail-notifications"
version = "0.1.0"
authors = ["Thomas <none>"]
edition = "2018"

[[bin]]
name = "systemd-fail-notifications"
path = "src/main.rs"

[dependencies]
zbus = "1.9.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.40"
serde_json = "1.0.64"
chrono = "0.4.19"
reqwest = { version = "0.11.3", features = ["blocking", "json"] }
