[package]
name = "systemd-webhooks"
version = "0.1.0"
authors = ["Thomas <none>"]
edition = "2018"

[[bin]]
name = "systemd-webhooks"
path = "src/main.rs"

[dependencies]
zbus = "1.9.1"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.40"
