name: cargo test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch cargo-about dependency
      run: cargo install cargo-about
    - name: Run tests
      run: cargo test --verbose
